DROP TABLE IF EXISTS film_db;
CREATE DATABASE film_db;
USE film_db;

DROP TABLE IF EXISTS films;
CREATE TABLE films(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
watched BOOLEAN DEFAULT false,
PRIMARY KEY(id)
);

